### ISSUE TITLE
No output to stdout when no TTY attached in Docker container

### ISSUE THREAD

**Issue by hauleth** [Stebalien/term#79]
You can see this on [Asciinema](https://asciinema.org/a/Zt7vTM8QykmGA2RpcCTOtepBR)

[This is my code that causes the issue](https://github.com/hauleth/geopost/tree/02cc12a629c33cf84875682d00ea4b535e60f3f3).

I would expect to be some output (no need for colouring of course).

I will try to produce minimal example when I will have some time.

**Comment by dpc** [comment]
@hauleth  I'm sorry. I think I made a mistake. I've looked more into it, and I believe the reason is, that you don't have `TERM` environment variable defined in your container, or there's something wrong with your term database, and https://github.com/slog-rs/term/blob/master/src/lib.rs#L1193 returns `None` which leads no logging at all.

**Comment by hauleth** [comment]
@dpc yeah, I have found this also. Should I open issue in slog-rs/slog for that? I think that this is soudness problem.
